version: '3.8'

services:
  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"  # Map container port 27017 to host port 27017

  mongo-express:
    image: mongo-express:latest
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin  # Optional for authentication
      - ME_CONFIG_MONGODB_AUTH_USERNAME=${MONGO_ROOT_USER}  # Optional for authentication
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=${MONGO_ROOT_PASSWORD}  # Optional for authentication
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_EXPRESS_USERNAME}  # Optional for Mongo Express basic auth
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_EXPRESS_PASSWORD}  # Optional for Mongo Express basic auth
    ports:
      - "8081:8081"
    depends_on:
      - mongo

volumes:
  mongo-data: {}